---
title: "Initial Network Analysis Florentine Family"
description: |
  Homework 2: Brief Analysis of the Florentine Family Set
author:
  - name: Noah Milstein
date: 2022-01-31
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}

library(network)

library(igraph)

```

```{r}

data(flo, package="network")

matrix <- as.matrix(flo) 

florentine<- graph.adjacency(flo, mode="directed", weighted=NULL)

plot(florentine)

```

```{r}

vcount(florentine)

ecount(florentine)

```

```{r}

is_bipartite(florentine)

is_directed(florentine)

is_weighted(florentine)

```

```{r}

vertex_attr_names(florentine)

edge_attr_names(florentine)

```

```{r}

igraph::dyad.census(florentine)

```

```{r}

igraph::triad_census(florentine)

```

```{r}

transitivity(florentine, type="global")

```

```{r}

transitivity(florentine, type="average")

```

```{r}

V(florentine)[c("Peruzzi","Lamberteschi", "Ginori")]

```

```{r}
transitivity(florentine, type="local", vids=V(florentine)[c("Peruzzi","Lamberteschi", "Ginori")]) 
```

```{r}

distances(florentine,"Peruzzi", "Lamberteschi")

```

```{r}

distances(florentine,"Peruzzi", "Ginori")

```

```{r}

distances(florentine,"Lamberteschi","Ginori")

```

