---
title: "Work_with_Medieval_Networks"
description: |
  A short description of the post.
author:
  - name: Noah Milstein
    url: {}
date: 2022-02-10
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}

library(readxl)
library(igraph)
library(statnet)
library(network)
library(tidyverse)
```

```{r}

wars_in_medieval_2 <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_medieval_2.xlsx")

wars_in_medieval_2$"Out-list" <- sapply(wars_in_medieval_2$"Out-list",
                                    function(x) { gsub("[\r\n]", "", x) })
wars_in_medieval_2$"In-list"<- sapply(wars_in_medieval_2$"In-list",
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_medieval_2
```

```{r}

wars_in_medieval_2_test <- data.frame(ThreadID = c(wars_in_medieval_2$"In-list"),
                 AuthorID = c(wars_in_medieval_2$"Out-list"))
wars_in_medieval_2_test_2 <- dplyr::inner_join(wars_in_medieval_2_test, wars_in_medieval_2_test, by = "ThreadID")[,-1]
wars_in_medieval_2_test_3 <- apply(wars_in_medieval_2_test_2, 2, as.character)

```

```{r}

set.seed(2)

wars_in_medieval_2.ig<-graph_from_data_frame(wars_in_medieval_2)

clp <- cluster_label_prop(wars_in_medieval_2.ig)

plot(clp, wars_in_medieval_2.ig, vertex.size=2,  edge.arrow.size=.1, vertex.color="gold", vertex.size=20, vertex.frame.color="gray", vertex.label.color="black", vertex.label.cex=0.3, vertex.label.dist=2, edge.curved=0.2)

```

```{r}

set.seed(2)


wars_in_medieval_2.ig<-graph_from_data_frame(wars_in_medieval_2)

clp <- cluster_label_prop(wars_in_medieval_2.ig)

plot(clp, wars_in_medieval_2.ig, vertex.size=2,  edge.arrow.size=.1, vertex.color="gold", vertex.size=20, vertex.frame.color="gray", vertex.label.color="black", vertex.label.cex=0.3, vertex.label.dist=2, edge.curved=0.2)
```

```{r}

set.seed(2)

medieval_wars_3 <- read_excel("~/Desktop/Spring 2022/Networks/medieval_wars_2.xlsx")

wars_in_medieval_3_test <- data.frame(ThreadID = c(medieval_wars_3$"In"),
                 AuthorID = c(medieval_wars_3$"Out"))
wars_in_medieval_3_test_2 <- dplyr::inner_join(wars_in_medieval_3_test, wars_in_medieval_3_test, by = "ThreadID")[,-1]
wars_in_medieval_3_test_3 <- apply(wars_in_medieval_3_test_2, 2, as.character)

wars_in_medieval_3.ig<-graph_from_data_frame(medieval_wars_3)

clp_med3 <- cluster_label_prop(wars_in_medieval_3.ig)

plot(clp_med3, wars_in_medieval_3.ig, vertex.size=2,  edge.arrow.size=.1, vertex.color="gold", vertex.size=20, vertex.frame.color="gray", vertex.label.color="black", vertex.label.cex=0.3, vertex.label.dist=2, edge.curved=0.2)

```


```{r}

igraph::dyad.census(wars_in_medieval_2.ig)

```
```{r}

igraph::triad.census(wars_in_medieval_2.ig)

```

```{r}

transitivity(wars_in_medieval_2.ig, type="global")

transitivity(wars_in_medieval_2.ig, type="average")

```


```{r}

graph.density(wars_in_medieval_2.ig, loops=TRUE)

graph.density(wars_in_medieval_3.ig, loops=TRUE)

```

```{r}

library(intergraph)

```

```{r}
medieval_network <- asNetwork(wars_in_medieval_2.ig)

medieval.nodes<-data.frame(name=medieval_network%v%"vertex.names", degree=sna::degree(medieval_network))

medieval.nodes

summary(medieval.nodes)
```


```{r}

medieval.nodes[order(-medieval.nodes$degree),]

```

```{r}
summary(medieval.nodes)
```

